### ISSUE TITLE
Anko DSL preview creates Exception and prevents *any* kotlin project to Load in AS 1.2

### ISSUE THREAD

**Issue by vladp** [JetBrains/anko#55] opened 2015-06-01 06:22 UTC
Windows 8.1 64 / android-studio-bundle-141.1903250-windows / Kotln 0.12.200

Error when opening any Kotlin project:

"Cannot load project: com.itellij.ide.plugins.PluginManager$StartupAbortedException:
com.intellij.diagnostic.PluginException:
kotlin.properties.Delegates.lazy(Lkotlin/Function0;)LKotlin/properties/ReadOnlyProperty;(Plugin:org.jetbrains.kotlin.android.dsl)"

**Comment by yanex** [comment] 2015-06-01 14:31
The problem is being fixed now.
Sorry for the inconvenience!

**Comment by yanex** [comment] 2015-06-04 15:12
Fixed!

**Closed by yanex** 2015-06-04 15:12 UTC
